# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-imcyto-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:

  ## conda-forge packages
  - python=2.7.15
  - pip=19.0.3
  - cython=0.29.6
  - r-base=3.4.1
  - r-markdown=0.8

  - boto3=1.9.106
  - docutils=0.14
  - h5py=2.9.0
  - joblib=0.13.2
  - mahotas=1.4.5
  - matplotlib=2.2.3
  - mysqlclient==1.3.13
  - numpy=1.16.2
  - pyzmq==15.3.0
  - raven=6.10.0
  - requests=2.21.0
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - six=1.12.0
  - wxpython=3.0.0.0

  ## bioconda packages
  - java-jdk=8.0.92
  - imctools=0.2
  - prokaryote=2.4.1

  ## install CellProfiler
  - pip:
    - git+https://github.com/CellProfiler/CellProfiler.git@v3.1.8
